version: '3.4'

services:
  audiostreamer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  stream.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

