version: '3.4'

services:
  audiostreamer:
    image: audiostreamer
    build:
      context: ./WebFront/AudioStreamer
      dockerfile: Dockerfile
    ports: 
      - "8080:4200"

  stream.api:
    image: ${DOCKER_REGISTRY-}streamapi
    build:
      context: .
      dockerfile: Microservices/Stream/Stream.API/Dockerfile
    ports: 
      - "8081:80"
